@startuml





/' Objects '/

class Handler {
	-mName : std::string
	-mState : handler_state_e
	-mTotalWork : uint64_t
	-mWorkLog : uint64_t
	-mTaskQueue : SafeQueue<uint64_t>
	-ServerNotifier : void*
	+Handler()
	+Handler(void* serverNotifier)
	+~Handler()
	-CheckAvailableTask() : bool
	-SetState(handler_state_e newState) : void
	+ReceiveTask(uint64_t task) : void
	+ExecuteTask() : void
	+GetName() : std::string
	+GetState() : handler_state_e
	+GetWorkLog() : uint64_t
	+GetTotalWork() : uint64_t
	+LogWork(uint64_t workLog) : void
}


class SafeQueue <template<class T>> {
	-q : std::queue<T>
	-m : mutable std::mutex
	-c : std::condition_variable
	+SafeQueue()
	+~SafeQueue()
	+empty() : bool {query}
	+size() : unsigned long {query}
	+front() : T
	+back() : T
	+push(T t) : void
	+pop() : T
}


class Server {
	-mRequirementPath : std::string
	-mListHandlers : std::vector<HandlerPtr>
	-mListTasks : SafeQueue<uint64_t>
	-mNumberOfHandlers : uint8_t
	-mMaxHandlers : uint8_t
	+Server()
	+Server(std::string& rFilePath)
	+~Server()
	+UpdateRequirementPath(std::string& rFilePath) : void
	+GetRequirement() : void
	+SortRequirement() : void
	+AssignTask() : void
	+DecreaseNumberOfActiveHandlers() : void
	+WriteReport() : void
	+ReadReport() : void
}


enum HANDLER_STATE_E {
	ACTIVE
	INACTIVE
}





/' Inheritance relationships '/




/' Aggregation relationships '/

.Handler *-- .SafeQueue


.Server *-- .SafeQueue






/' Nested objects '/



@enduml
